version: '3'
services:
  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecret
    volumes:
      - db-data-hackathon:/var/lib/postgresql/data

volumes:
  db-data-hackathon: